import type {
  PublicGearDeployment,
  PublicMemberLocation,
} from "@/lib/fafo-world/domain";

const UNKNOWN_STATIC_TIMELINE = {
  createdAt: null,
  updatedAt: null,
  publishedAt: null,
} as const;

export const STATIC_GEAR_DEPLOYMENTS = [
  {
    id: "gear-vancouver-bc-001",
    city: "Vancouver",
    region: "British Columbia",
    country: "Canada",
    latitude: 49.2827,
    longitude: -123.1207,
    category: "STANDARD_GEAR",
    markerType: "standard-deployment",
    publicLabel: "FAFO Gear Deployed",
    timeline: UNKNOWN_STATIC_TIMELINE,
  },
  {
    id: "gear-chemainus-bc-001",
    city: "Chemainus",
    region: "British Columbia",
    country: "Canada",
    latitude: 48.9208,
    longitude: -123.7165,
    category: "STANDARD_GEAR",
    markerType: "standard-deployment",
    publicLabel: "FAFO Gear Deployed",
    timeline: UNKNOWN_STATIC_TIMELINE,
  },
  {
    id: "gear-cedar-city-ut-001",
    city: "Cedar City",
    region: "Utah",
    country: "USA",
    latitude: 37.6775,
    longitude: -113.0619,
    category: "GOLD_STAR_CUSTOM",
    markerType: "gold-star-fafo",
    publicLabel: "Gold Star FAFO Custom Deployment",
    timeline: UNKNOWN_STATIC_TIMELINE,
  },
  {
    id: "gear-cedar-city-ut-002",
    city: "Cedar City",
    region: "Utah",
    country: "USA",
    latitude: 37.6775,
    longitude: -113.0619,
    category: "GOLD_STAR_CUSTOM",
    markerType: "gold-star-fafo",
    publicLabel: "Gold Star FAFO Custom Deployment",
    timeline: UNKNOWN_STATIC_TIMELINE,
  },
  {
    id: "gear-calgary-ab-001",
    city: "Calgary",
    region: "Alberta",
    country: "Canada",
    latitude: 51.0447,
    longitude: -114.0719,
    category: "GOLD_STAR_CUSTOM",
    markerType: "gold-star-fafo",
    publicLabel: "Gold Star FAFO Custom Deployment",
    timeline: UNKNOWN_STATIC_TIMELINE,
  },
  {
    id: "gear-toronto-on-001",
    city: "Toronto",
    region: "Ontario",
    country: "Canada",
    latitude: 43.6532,
    longitude: -79.3832,
    category: "STANDARD_GEAR",
    markerType: "standard-deployment",
    publicLabel: "FAFO Gear Deployed",
    timeline: UNKNOWN_STATIC_TIMELINE,
  },
] as const satisfies readonly PublicGearDeployment[];

export const STATIC_MEMBER_LOCATIONS = [
  {
    id: "member-victoria-bc-001",
    city: "Victoria",
    region: "British Columbia",
    country: "Canada",
    latitude: 48.4284,
    longitude: -123.3656,
    category: "MEMBER_LOCATION",
    markerType: "fafo-member-location",
    role: "Founding Member / Owner",
    publicLabel: "FAFO Member Location",
    timeline: UNKNOWN_STATIC_TIMELINE,
  },
] as const satisfies readonly PublicMemberLocation[];
