export type PublicationState = "published" | "withheld" | "withhold-hat" | "withhold-hoodie" | "withhold-female-version" | "review-required" | "future";
export type CatalogClassification = "STORE_V1" | "WITHHOLD" | "CUSTOM_GALLERY" | "RESERVED_CUSTOM_ORDER" | "CUSTOM_REVIEW_REQUIRED" | "FUTURE_TRADES";
export type CatalogCollectionSlug = "apparel" | "drinkware" | "accessories" | "headwear" | "fafo-k9-gear" | "reserved-custom-orders" | "fafo-trades";
export type CatalogImage = { src: string; alt: string };
export type ExternalPurchaseDestination = { label: "Purchase on Printify"; url: string };
export type ProductServiceTier = "DEFAULT" | "PERSONALIZATION" | "CUSTOM_BUILD";
export type ProductCapabilityStatus = "AVAILABLE" | "REVIEW_REQUIRED" | "NOT_SUPPORTED";
export type ProductCapability = Readonly<{ tier: ProductServiceTier; available: boolean; status: ProductCapabilityStatus; notice?: string }>;
export type CatalogProduct = { slug: string; title: string; description?: string; priceCad: string; collection: CatalogCollectionSlug; classification: CatalogClassification; publicationState: PublicationState; image: CatalogImage; purchase: ExternalPurchaseDestination; capabilities: readonly ProductCapability[] };
export type CatalogCollection = { slug: CatalogCollectionSlug; name: string; description: string; publicationState: PublicationState };
export type CatalogInventoryRecord = Readonly<{ printifyProductId: string; title: string; url: string; publicationState: PublicationState; classification: CatalogClassification }>;

export const catalogCollections: CatalogCollection[] = [
  { slug: "apparel", name: "Apparel", description: "Approved Remastered FAFO Nation apparel.", publicationState: "published" },
  { slug: "drinkware", name: "Drinkware", description: "Approved Remastered FAFO Nation drinkware.", publicationState: "published" },
  { slug: "accessories", name: "Accessories", description: "Future collection capability; no approved Store V1 items currently published.", publicationState: "future" },
  { slug: "headwear", name: "Headwear", description: "Future collection capability; no approved Store V1 items currently published.", publicationState: "future" },
  { slug: "fafo-k9-gear", name: "FAFO K9 Gear", description: "Future collection capability; no approved Store V1 items currently published.", publicationState: "future" },
  { slug: "reserved-custom-orders", name: "Reserved / Custom Orders", description: "Items created for specific customers. No listings are published until intent is verified.", publicationState: "future" },
  { slug: "fafo-trades", name: "FAFO Trades", description: "Future collection capability. No products are published in this collection yet.", publicationState: "future" },
];

const customBuildEligibleProductSlugs = new Set(["becca-got-your-6", "becca-phoenix-rising", "becca-beating-cancer", "becky-fundraiser", "basic-consequence-meter", "basic-frag-em-all", "basic-man-in-black"]);
const capabilitiesFor = (slug: string): readonly ProductCapability[] => [{ tier: "DEFAULT", available: true, status: "AVAILABLE" }, { tier: "PERSONALIZATION", available: false, status: "REVIEW_REQUIRED", notice: "Personalization options for this product are being configured." }, customBuildEligibleProductSlugs.has(slug) ? { tier: "CUSTOM_BUILD", available: true, status: "AVAILABLE" } : { tier: "CUSTOM_BUILD", available: false, status: "NOT_SUPPORTED", notice: "Custom Build is not currently available for this product." }];
const listing = (slug: string, title: string, priceCad: string, collection: CatalogCollectionSlug, id: string, imagePath: string, query: string, listingPath: string): CatalogProduct => ({ slug, title, priceCad, collection, classification: "STORE_V1", publicationState: "published", image: { src: `https://images-api.printify.com/mockup/${id}/${imagePath}?${query}`, alt: title }, purchase: { label: "Purchase on Printify", url: `https://fafo-nation-hq.printify.me/product/${listingPath}` }, capabilities: capabilitiesFor(slug) });

export const catalogProducts: CatalogProduct[] = [
  listing("becca-got-your-6", "FAFO Cares Becca Beating Cancer Got your 6 Remastered T Shirt", "CA$41.61", "apparel", "6a46b7244144d0b569037155", "83516/51812/fafo-cares-becca-beating-cancer-got-your-6-remastered-t-shirt.jpg", "camera_label=front&revision=1786454374005", "29716703/fafo-cares-becca-beating-cancer-got-your-6-remastered-t-shirt"),
  listing("becca-phoenix-rising", "FAFO Cares Becca Beating Cancer Phoenix Rising Remastered T Shirt", "CA$41.61", "apparel", "6a46882745705605d90ff271", "12100/92570/fafo-cares-becca-beating-cancer-phoenix-rising-remastered-t-shirt.jpg", "camera_label=front&revision=1786428291247", "29713936/fafo-cares-becca-beating-cancer-phoenix-rising-remastered-t-shirt"),
  listing("becca-beating-cancer", "FAFO Cares Becca Beating Cancer Remastered T Shirt", "CA$36.06", "apparel", "6a467829b706a0bfc50e126e", "83516/51812/fafo-cares-becca-beating-cancer-remastered-t-shirt.jpg", "camera_label=front&revision=1786427018363", "29713724/fafo-cares-becca-beating-cancer-remastered-t-shirt"),
  listing("becky-fundraiser", "FAFO Love: Becky Beating Cancer Remastered Fundraiser Shirt", "CA$41.61", "apparel", "6a34b6f0722a0b482e1061ed", "43088/647/fafo-love-becky-beating-cancer-remastered-fundraiser-shirt.jpg", "camera_label=left-side&revision=1786454391874", "29396755/fafo-love-becky-beating-cancer-remastered-fundraiser-shirt"),
  listing("creasy-clean-logo-mug", "FAFO Nation Creasy Clean Remastered Logo Mug", "CA$18.00", "drinkware", "6a347c7743bfb44afc0e065a", "78565/41702/fafo-nation-creasy-clean-remastered-logo-mug.jpg", "camera_label=left&revision=1786861880565", "29392435"),
  listing("dont-be-the-cattle-mug", "FAFO Nation Dont be the Cattle Remastered Coffee Mug", "CA$20.80", "drinkware", "6a347412522223b8000662bd", "78565/41702/fafo-nation-dont-be-the-cattle-remastered-coffee-mug.jpg", "camera_label=left&revision=1786434003672", "29391448/fafo-nation-dont-be-the-cattle-remastered-coffee-mug"),
  listing("glowing-grunt-mug", "FAFO Nation Glowing Grunt Remastered Coffee Mug", "CA$18.02", "drinkware", "6a3471da2d7d0f30ad01706b", "78565/41702/fafo-nation-glowing-grunt-remastered-coffee-mug.jpg", "camera_label=left&revision=1786428621299", "29391306/fafo-nation-glowing-grunt-remastered-coffee-mug"),
  listing("basic-consequence-meter", "FAFO Nation Basic Consequence Meter Remastered T Shirt", "CA$41.61", "apparel", "6a342d9c95ba471ed50266de", "63300/97993/fafo-nation-basic-consequence-meter-remastered-t-shirt.jpg", "camera_label=back&revision=1786434665174", "29390499/fafo-nation-basic-consequence-meter-remastered-t-shirt"),
  listing("basic-frag-em-all", "FAFO Nation Basic Frag em All Remastered T Shirt", "CA$41.61", "apparel", "6a342d9995ba471ed50266dd", "63300/97993/fafo-nation-basic-frag-em-all-remastered-t-shirt.jpg", "camera_label=back&revision=1786455364670", "29390404/fafo-nation-basic-frag-em-all-remastered-t-shirt"),
  listing("basic-man-in-black", "FAFO Nation Basic Man in Black Remastered T Shirt", "CA$41.61", "apparel", "6a342da095ba471ed50266df", "63300/97993/fafo-nation-basic-man-in-black-remastered-t-shirt.jpg", "camera_label=back&revision=1786433664641", "29390255/fafo-nation-basic-man-in-black-remastered-t-shirt"),
  listing("poker-cards", "Poker Cards", "CA$23.55", "accessories", "6a68dbae6c808ce66710085d", "87236/62433/poker-cards.jpg", "camera_label=front&revision=1785257320806", "30433703"),
  listing("glowinggrunt-fridge-magnet", "FAFO GlowingGrunt Magnet | Military Skull Fridge Magnet | Veteran Gift | Tactical Decor | Remastered", "CA$11.16", "accessories", "6a59c4081110bb7031070687", "109684/112563/fafo-glowinggrunt-magnet-military-skull-fridge-magnet-veteran-gift-tactical-decor-remastered.jpg", "camera_label=front&revision=1786946553018", "30113231"),
  listing("glowing-grunt-tactical-magnet", "FAFO Glowing Grunt Magnet | Military Skull Magnet | Veteran Gift | Tactical Magnet | Remastered", "CA$27.70", "accessories", "6a59bd6f61bf25dbeb056620", "399202/134466/fafo-glowing-grunt-magnet-military-skull-magnet-veteran-gift-tactical-magnet-remastered.jpg", "camera_label=front&revision=1786947085143", "30112888"),
  listing("sgt-swagger-playing-cards", "FAFO Nation SGT Swagger Never Forgets Playing Cards – Veteran Military Poker Deck – Collectible Card Art", "CA$27.70", "accessories", "6a59ba2a9db79920b604023b", "72763/16404/fafo-nation-sgt-swagger-never-forgets-playing-cards-veteran-military-poker-deck-collectible-card-art.jpg", "camera_label=front&revision=1784269990882", "30112802"),
  listing("lest-we-never-forget-tumbler", "FAFO Nation Lest We Never Forget 20oz Tumbler", "CA$37.41", "drinkware", "6a34865c843d619b7e0eb6c4", "78458/41630/fafo-nation-lest-we-never-forget-20oz-tumbler.jpg", "camera_label=left&revision=1781988125683", "29393134"),
  listing("consequence-meter-coffee-mug", "FAFO Nation Consequence Meter Remastered Coffee Mug", "CA$20.77", "drinkware", "6a3476ffd6390f32130980cf", "78565/41702/fafo-nation-consequence-meter-remastered-coffee-mug.jpg", "camera_label=left&revision=1786944626396", "29391807"),
  listing("basic-no-refunds-deaths-ace", "FAFO Nation Basic No Refunds on Consequences Remastered Deaths Ace", "CA$38.79", "apparel", "6a342da495ba471ed50266e0", "38192/97993/fafo-nation-basic-no-refunds-on-consequences-remastered-deaths-ace.jpg", "camera_label=back&revision=1786905736541", "29390159"),
  listing("deluxe-consequence-meter", "FAFO Nation Deluxe Consequence Meter T Shirt", "CA$55.42", "apparel", "6a342d81f04fab63ea048847", "18390/102045/fafo-nation-deluxe-consequence-meter-t-shirt.jpg", "camera_label=back-2&revision=1786904578999", "29390021"),
  listing("frag-em-all-deluxe", "FAFO Nation Frag em All Deluxe Remastered T Shirt", "CA$63.74", "apparel", "6a342d7cf04fab63ea048846", "12190/102006/fafo-nation-frag-em-all-deluxe-remastered-t-shirt.jpg", "camera_label=back-2&revision=1786410115589", "29389939"),
  listing("man-in-black-deluxe", "FAFO Nation Man in Black Deluxe Remastered T Shirt", "CA$55.42", "apparel", "6a342d75f04fab63ea048845", "38608/102045/fafo-nation-man-in-black-deluxe-remastered-t-shirt.jpg", "camera_label=back-2&revision=1786862347946", "29389736"),
];
export const reconciledNonPublishedInventory: readonly CatalogInventoryRecord[] = [
  { printifyProductId: "31060371", title: "FAFO No Refunds on Consequences Remastered Hoodie", url: "https://fafo-nation-hq.printify.me/product/31060371", publicationState: "withhold-hoodie", classification: "WITHHOLD" },
  { printifyProductId: "30632138", title: "Roughneck Nation Custom Closed-Back Structured Cap (Embroidery)", url: "https://fafo-nation-hq.printify.me/product/30632138", publicationState: "withhold-hat", classification: "WITHHOLD" },
  { printifyProductId: "30631972", title: "Roughneck Nation Custom Lucee & Baylee Hoodie (AOP)", url: "https://fafo-nation-hq.printify.me/product/30631972", publicationState: "review-required", classification: "CUSTOM_REVIEW_REQUIRED" },
  { printifyProductId: "29705202", title: "The Jimi Custom Vertical Flag", url: "https://fafo-nation-hq.printify.me/product/29705202", publicationState: "review-required", classification: "CUSTOM_REVIEW_REQUIRED" },
];
export const publishedProducts = catalogProducts.filter((product) => product.publicationState === "published");
export const getProduct = (slug: string) => publishedProducts.find((product) => product.slug === slug);
export const getCollection = (slug: string) => catalogCollections.find((collection) => collection.slug === slug);
export const productCapability = (product: CatalogProduct, tier: ProductServiceTier) => product.capabilities.find((capability) => capability.tier === tier);
