import type { Metadata } from "next";
import Link from "next/link";
import Header from "../../Header";

export const metadata: Metadata = { title: "Member Spotlights", description: "Learn about the planned FAFO Nation space for approved member stories and contributions." };

export default function MemberSpotlightsPage() {
  return <main className="min-h-screen bg-black text-white"><Header /><section className="relative overflow-hidden border-b border-white/10 px-5 py-20 sm:px-10 sm:py-24 lg:px-16 lg:py-32"><div aria-hidden="true" className="pointer-events-none absolute left-1/2 top-0 h-[540px] w-[900px] max-w-full -translate-x-1/2 bg-[radial-gradient(circle,rgba(127,29,29,0.18)_0%,rgba(0,0,0,0)_68%)]" /><div className="relative z-10 mx-auto w-full max-w-7xl"><p className="text-xs font-black uppercase tracking-[0.32em] text-red-600">Community Stories</p><h1 className="mt-5 max-w-6xl text-5xl font-black uppercase leading-[0.9] tracking-[-0.05em] sm:text-7xl lg:text-9xl">Member <span className="block text-[#D4AF37]">Spotlights</span></h1><div className="mt-8 h-px w-24 bg-red-600" /><p className="mt-8 max-w-3xl text-base font-medium leading-8 text-white/65 sm:text-lg sm:leading-9">Member Spotlights is planned as a place to recognize people, stories, and contributions shared with permission by the FAFO Nation community.</p></div></section><section className="px-5 py-20 sm:px-10 sm:py-24 lg:px-16 lg:py-32"><div className="mx-auto w-full max-w-5xl border border-[#D4AF37]/30 bg-[#D4AF37]/[0.03] p-7 text-center sm:p-12"><p className="text-xs font-black uppercase tracking-[0.24em] text-[#D4AF37]">Spotlights — Coming Later</p><h2 className="mt-5 text-3xl font-black uppercase sm:text-5xl">Stories Require Consent</h2><p className="mx-auto mt-6 max-w-3xl text-base leading-8 text-white/60">No member profiles, names, testimonials, awards, or personal stories are currently published here. Future spotlights will require approved content and member-controlled participation.</p><Link href="/community" className="mt-9 inline-flex min-h-12 items-center border border-red-600/70 px-7 py-3 text-xs font-black uppercase tracking-[0.18em] text-[#D4AF37] transition hover:bg-red-700/30 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-red-600">Explore Community</Link></div></section></main>;
}
