import type { Metadata } from "next";
import Link from "next/link";
import Header from "../../Header";

export const metadata: Metadata = { title: "Videos", description: "Access the existing public FAFO Nation video destination." };

export default function VideosPage() {
  return <main className="min-h-screen bg-black text-white"><Header /><section className="relative overflow-hidden border-b border-white/10 px-5 py-20 sm:px-10 sm:py-24 lg:px-16 lg:py-32"><div aria-hidden="true" className="pointer-events-none absolute left-1/2 top-0 h-[540px] w-[900px] max-w-full -translate-x-1/2 bg-[radial-gradient(circle,rgba(127,29,29,0.18)_0%,rgba(0,0,0,0)_68%)]" /><div className="relative z-10 mx-auto w-full max-w-7xl"><p className="text-xs font-black uppercase tracking-[0.32em] text-red-600">Media & Content</p><h1 className="mt-5 text-5xl font-black uppercase leading-[0.9] tracking-[-0.05em] sm:text-7xl lg:text-9xl">FAFO <span className="block text-[#D4AF37]">Videos</span></h1><div className="mt-8 h-px w-24 bg-red-600" /><p className="mt-8 max-w-3xl text-base font-medium leading-8 text-white/65 sm:text-lg sm:leading-9">FAFO Nation’s existing public YouTube destination is available below. The website does not currently maintain its own video catalog or claim a release schedule.</p></div></section><section className="px-5 py-20 sm:px-10 sm:py-24 lg:px-16 lg:py-32"><div className="mx-auto w-full max-w-5xl border border-white/15 bg-white/[0.02] p-7 text-center sm:p-12"><p className="text-xs font-black uppercase tracking-[0.24em] text-[#D4AF37]">External Public Channel</p><h2 className="mt-5 text-3xl font-black uppercase sm:text-5xl">FAFO Nation on YouTube</h2><p className="mx-auto mt-6 max-w-2xl text-base leading-8 text-white/60">This link opens the public FAFO Nation YouTube channel in a new tab.</p><div className="mt-9 flex flex-wrap justify-center gap-4"><a href="https://www.youtube.com/@FAFONationHQ" target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center border border-red-600/70 px-7 py-3 text-xs font-black uppercase tracking-[0.18em] text-[#D4AF37] transition hover:bg-red-700/30 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-red-600">Open YouTube</a><Link href="/media" className="inline-flex min-h-12 items-center border border-white/20 px-7 py-3 text-xs font-black uppercase tracking-[0.18em] text-white transition hover:bg-white/5 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-white">Back to Media</Link></div></div></section></main>;
}
