import type { Metadata } from "next";
import Image, { type StaticImageData } from "next/image";
import Header from "../../Header";
import { secretSolver } from "./_lib/fonts";
import ContextualRightsFooter from "../../_components/ContextualRightsFooter";
import banner from "../../../assets/velvet-witch/velvet-witch-banner.png";
import bloodRush from "../../../assets/velvet-witch/blood-rush.jpg";
import findOut from "../../../assets/velvet-witch/find-out.jpg";
import rockRange from "../../../assets/velvet-witch/rock-range-showcase.jpg";
import wiresLoose from "../../../assets/velvet-witch/wires-first.jpg";
import { velvetWitchContent } from "./_lib/velvetWitchContent";

export const metadata: Metadata = { title: "The Velvet Witch Universe", description: "Velvet Witch turns real life, emotional honesty, and independent creative control into music." };
const externalLinkClass = "inline-flex min-h-11 items-center justify-center border border-[#d682a8]/70 px-5 text-xs font-bold uppercase tracking-[0.16em] text-[#D4AF37] transition hover:border-[#f7c4d8] hover:bg-[#b55a83]/15 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#f7c4d8]";
function ExternalLink({ href, children }: Readonly<{ href: string; children: React.ReactNode }>) { return <a href={href} target="_blank" rel="noopener noreferrer" className={externalLinkClass}>{children}<span aria-hidden="true">&nbsp;↗</span></a>; }
function Artwork({ src, alt, priority = false }: Readonly<{ src: StaticImageData; alt: string; priority?: boolean }>) { return <Image src={src} alt={alt} priority={priority} className="h-auto w-full" sizes="(min-width: 1280px) 1200px, (min-width: 768px) 90vw, 100vw" />; }

export default function FeaturedArtistPage() {
  const { destinations, artistStatement, projects, fafoConnection } = velvetWitchContent;
  const artwork = [wiresLoose, bloodRush, rockRange];
  return <main className="min-h-screen bg-[#090609] text-[#f8eef3]"><Header />
    <section className="border-b border-[#b55a83]/30 bg-[#0e080d] px-5 py-8 sm:px-10 sm:py-12 lg:px-16" aria-labelledby="velvet-witch-title"><div className="mx-auto w-full max-w-7xl"><p className="mb-5 text-xs font-bold uppercase tracking-[0.34em] text-[#B72089]">FAFO Nation featured artist</p><div className="relative left-1/2 w-[min(95vw,1536px)] -translate-x-1/2"><Artwork src={banner} alt="Velvet Witch Universe" priority /></div><div className="mt-8 grid gap-7 lg:grid-cols-[1.35fr_0.65fr] lg:items-end"><div><h1 id="velvet-witch-title" className={`${secretSolver.className} velvet-witch-display text-5xl font-black uppercase leading-[0.9] tracking-[-0.06em] text-[#B72089] sm:text-7xl`}><span className="block">The Velvet Witch</span><span className="block text-[#D4AF37]">Universe</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-red-600 sm:text-xl">Music, Stories and a World built one release at a time—on her own terms.</p></div><div className="flex flex-wrap gap-3 lg:justify-end"><ExternalLink href={destinations.youtube}>Watch on YouTube</ExternalLink><ExternalLink href={destinations.spotify}>Listen on Spotify</ExternalLink></div></div></div></section>
    <section className="px-5 py-14 sm:px-10 sm:py-[5.25rem] lg:px-16" aria-labelledby="projects-heading"><div className="mx-auto w-full max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#B72089]">Listen to the story</p><h2 id="projects-heading" className={`${secretSolver.className} mt-[0.875rem] velvet-witch-display text-4xl font-black uppercase tracking-[-0.04em] text-[#D4AF37] sm:text-6xl`}>Projects become worlds.</h2><div className="mt-[2.625rem] grid gap-8 lg:grid-cols-3">{projects.map((project, index) => <article key={project.title} className="flex flex-col border border-[#b55a83]/30 bg-[#160a14]"><Artwork src={artwork[index]} alt={`${project.title} by Velvet Witch`} /><div className="flex flex-1 flex-col p-6"><p className="text-[11px] font-bold uppercase tracking-[0.22em] text-[#B72089]">{project.eyebrow}</p><h3 className={`${secretSolver.className} mt-[1.125rem] velvet-witch-display text-2xl font-black uppercase text-[#D4AF37]`}>{project.title}</h3><p className="mt-[0.875rem] text-sm leading-7 text-red-600">{project.description}</p><div className="mt-auto pt-6"><ExternalLink href={project.href}>{project.linkLabel}</ExternalLink></div></div></article>)}</div></div></section>
    <section className="border-y border-[#b55a83]/25 bg-[#160a14] px-5 py-14 sm:px-10 sm:py-[5.25rem] lg:px-16" aria-labelledby="find-out-heading"><div className="mx-auto grid w-full max-w-7xl gap-9 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><Artwork src={findOut} alt="Find Out by Velvet Witch" /><div><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#B72089]">The FAFO connection</p><h2 id="find-out-heading" className={`${secretSolver.className} mt-[0.875rem] velvet-witch-display text-4xl font-black uppercase tracking-[-0.04em] text-[#D4AF37] sm:text-6xl`}>Find Out.</h2><p className="mt-[1.3125rem] text-lg leading-8 text-red-600">{fafoConnection}</p><div className="mt-7"><ExternalLink href="https://youtu.be/EJx1gqex2Uw?si=gsjI-B7oiAAybRcY">Watch Find Out</ExternalLink></div></div></div></section>
    <section className="px-5 py-14 sm:px-10 sm:py-[5.25rem] lg:px-16" aria-labelledby="artist-heading"><div className="mx-auto grid w-full max-w-7xl gap-9 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#B72089]">Artist / creative world</p><h2 id="artist-heading" className={`${secretSolver.className} mt-[0.875rem] velvet-witch-display text-4xl font-black uppercase tracking-[-0.04em] text-[#D4AF37] sm:text-6xl`}>Every Word Is Hers</h2></div><div className="max-w-2xl space-y-[1.3125rem] text-base leading-8 text-red-600 sm:text-lg">{artistStatement.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div></section>
    <section className="border-y border-white/10 bg-[#0d080d] px-5 py-14 sm:px-10 sm:py-[5.25rem] lg:px-16" aria-labelledby="support-heading"><div className="mx-auto grid w-full max-w-7xl gap-9 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#B72089]">Own / support the music</p><h2 id="support-heading" className={`${secretSolver.className} mt-[0.875rem] velvet-witch-display text-4xl font-black uppercase tracking-[-0.04em] text-[#D4AF37] sm:text-6xl`}>Take the Story With You</h2><p className="mt-[1.125rem] max-w-xl text-base leading-8 text-red-600">Support the writing directly through official music downloads, or wear a piece of the universe through the live Velvet Witch store.</p></div><div className="flex flex-wrap content-center gap-3"><ExternalLink href={destinations.payhip}>Music downloads</ExternalLink><ExternalLink href={destinations.fourthwall}>Wear the universe</ExternalLink><ExternalLink href={destinations.youtube}>New releases</ExternalLink></div></div></section>
    <ContextualRightsFooter brand="Velvet Witch"><span>Images, Audio, Video and other Velvet Witch creative material featured on this page belong to Velvet Witch and their respective rights holders. Fan artwork by NRDC.</span></ContextualRightsFooter></main>;
}
