import type { Money } from "../money.ts";
import { addMoney, createMoney, createOrderItem, orderId, type Cart, type CheckoutSession, type CommerceIdentifier, type CommercialItemSnapshot, type FulfillmentState, type OrderItem, type OrderState, type PaymentState, type ProductionState, type ShipmentState } from "./core.ts";
import type { CheckoutReadiness } from "./orchestration.ts";

export type RecoveryDisposition = "RETRYABLE" | "NON_RETRYABLE" | "RECONCILIATION_REQUIRED" | "CUSTOMER_ACTION_REQUIRED" | "MANUAL_REVIEW_REQUIRED";
export type FakeOutcome = "AUTHORIZED" | "CAPTURED" | "REQUIRES_ACTION" | "FAILED" | "UNAVAILABLE" | "TIMEOUT_BEFORE" | "TIMEOUT_AFTER_SUCCESS" | "AMBIGUOUS" | "ACCEPTED" | "REJECTED";
export type ProviderResult = Readonly<{ state: "SUCCESS" | "FAILED" | "UNKNOWN" | "REQUIRES_ACTION"; providerReference: string; disposition: RecoveryDisposition; detail?: string }>;
export type ManualReview = Readonly<{ reason: string; operation: "PAYMENT" | "FULFILLMENT" | "CANCELLATION" | "REFUND"; customerActionRequired: boolean; operatorActionRequired: boolean }>;
export type TransactionOrder = Readonly<{ id: CommerceIdentifier<"OrderId">; state: OrderState; items: readonly OrderItem[]; subtotal: Money; checkoutId: CommerceIdentifier<"CheckoutSessionId">; cartVersion: number }>;
export type CommerceTransaction = Readonly<{ order: TransactionOrder; payment: PaymentState | "UNKNOWN"; fulfillment: FulfillmentState | "UNKNOWN"; production: ProductionState; shipment: ShipmentState; reviews: readonly ManualReview[]; events: readonly CommerceEvent[] }>;
export type CommerceEvent = Readonly<{ id: string; operation: "PAYMENT" | "FULFILLMENT" | "PRODUCTION" | "SHIPMENT" | "REFUND"; state: string; occurredAt: string; sequence: number }>;

function subtotal(cart: Cart): Money { const first = cart.items[0]; if (!first) throw new Error("Order requires at least one cart line."); const total = cart.items.reduce<Money | null>((sum, line) => { const value = createMoney(line.snapshot.unitPrice.minorUnits * line.snapshot.quantity, line.snapshot.unitPrice.currency); return sum && value ? addMoney(sum, value) : null; }, createMoney(0, first.snapshot.unitPrice.currency)); if (!total) throw new Error("Order lines must share one currency."); return total; }
export class InMemoryOrderService {
  private readonly byKey = new Map<string, TransactionOrder>();
  submit(input: { id: string; key: string; cart: Cart; checkout: CheckoutReadiness }): TransactionOrder {
    if (input.checkout.status !== "READY_FOR_PAYMENT" || input.checkout.session.state !== "READY") throw new Error("Checkout is not ready for payment.");
    const fingerprint = `${input.cart.id}:${input.cart.version}`; const existing = this.byKey.get(input.key);
    if (existing) { if (`${existing.checkoutId}:${existing.cartVersion}` !== `${input.checkout.session.id}:${input.cart.version}`) throw new Error("Conflicting order idempotency key."); return existing; }
    const order: TransactionOrder = Object.freeze({ id: orderId(input.id), state: "SUBMITTED", checkoutId: input.checkout.session.id, cartVersion: input.cart.version, items: Object.freeze(input.cart.items.map((line, index) => createOrderItem(`${input.id}-line-${index + 1}`, line.snapshot))), subtotal: subtotal(input.cart) });
    this.byKey.set(input.key, order); return order;
  }
}

/** Deterministic in-memory provider. TIMEOUT_AFTER_SUCCESS is deliberately unknown locally but recorded externally for reconciliation. */
export class FakePaymentProvider {
  private readonly effects = new Map<string, PaymentState>();
  constructor(private readonly scenarios: Readonly<Record<string, FakeOutcome>> = {}) {}
  capture(key: string): ProviderResult { const existing = this.effects.get(key); if (existing === "CAPTURED") return { state: "SUCCESS", providerReference: key, disposition: "NON_RETRYABLE" }; const outcome = this.scenarios[key] ?? "CAPTURED"; if (outcome === "CAPTURED" || outcome === "TIMEOUT_AFTER_SUCCESS") { this.effects.set(key, "CAPTURED"); return outcome === "CAPTURED" ? { state: "SUCCESS", providerReference: key, disposition: "NON_RETRYABLE" } : { state: "UNKNOWN", providerReference: key, disposition: "RECONCILIATION_REQUIRED", detail: "response lost after external capture" }; } if (outcome === "AUTHORIZED") { this.effects.set(key, "AUTHORIZED"); return { state: "SUCCESS", providerReference: key, disposition: "NON_RETRYABLE" }; } if (outcome === "REQUIRES_ACTION") return { state: "REQUIRES_ACTION", providerReference: key, disposition: "CUSTOMER_ACTION_REQUIRED" }; if (outcome === "AMBIGUOUS") return { state: "UNKNOWN", providerReference: key, disposition: "RECONCILIATION_REQUIRED" }; return { state: "FAILED", providerReference: key, disposition: outcome === "UNAVAILABLE" || outcome === "TIMEOUT_BEFORE" ? "RETRYABLE" : "NON_RETRYABLE" }; }
  refund(key: string): ProviderResult { const outcome = this.scenarios[`refund:${key}`] ?? "CAPTURED"; return outcome === "CAPTURED" ? { state: "SUCCESS", providerReference: `refund:${key}`, disposition: "NON_RETRYABLE" } : outcome === "AMBIGUOUS" ? { state: "UNKNOWN", providerReference: `refund:${key}`, disposition: "RECONCILIATION_REQUIRED" } : { state: "FAILED", providerReference: `refund:${key}`, disposition: "RETRYABLE" }; }
  reconcile(key: string): PaymentState | "UNKNOWN" { return this.effects.get(key) ?? "UNKNOWN"; }
}
export class FakeFulfillmentProvider {
  private readonly effects = new Map<string, FulfillmentState>();
  constructor(private readonly scenarios: Readonly<Record<string, FakeOutcome>> = {}) {}
  submit(key: string): ProviderResult { const existing = this.effects.get(key); if (existing === "ACCEPTED") return { state: "SUCCESS", providerReference: key, disposition: "NON_RETRYABLE" }; const outcome = this.scenarios[key] ?? "ACCEPTED"; if (outcome === "ACCEPTED" || outcome === "TIMEOUT_AFTER_SUCCESS") { this.effects.set(key, "ACCEPTED"); return outcome === "ACCEPTED" ? { state: "SUCCESS", providerReference: key, disposition: "NON_RETRYABLE" } : { state: "UNKNOWN", providerReference: key, disposition: "RECONCILIATION_REQUIRED", detail: "response lost after external acceptance" }; } if (outcome === "AMBIGUOUS") return { state: "UNKNOWN", providerReference: key, disposition: "RECONCILIATION_REQUIRED" }; return { state: "FAILED", providerReference: key, disposition: outcome === "UNAVAILABLE" || outcome === "TIMEOUT_BEFORE" ? "RETRYABLE" : "NON_RETRYABLE" }; }
  reconcile(key: string): FulfillmentState | "UNKNOWN" { return this.effects.get(key) ?? "UNKNOWN"; }
}

export function beginTransaction(order: TransactionOrder, production: ProductionState = "NOT_REQUIRED", shipment: ShipmentState = "NOT_REQUIRED"): CommerceTransaction { return Object.freeze({ order, payment: "PENDING", fulfillment: "NOT_REQUESTED", production, shipment, reviews: Object.freeze([]), events: Object.freeze([]) }); }
function review(transaction: CommerceTransaction, item: ManualReview): CommerceTransaction { return Object.freeze({ ...transaction, reviews: Object.freeze([...transaction.reviews, item]) }); }
export function capturePayment(transaction: CommerceTransaction, provider: FakePaymentProvider, key: string): CommerceTransaction { const result = provider.capture(key); if (result.state === "SUCCESS") return Object.freeze({ ...transaction, payment: result.providerReference && provider.reconcile(key) === "CAPTURED" ? "CAPTURED" : "AUTHORIZED", order: { ...transaction.order, state: "CONFIRMED" as OrderState } }); if (result.state === "REQUIRES_ACTION") return Object.freeze({ ...transaction, payment: "REQUIRES_ACTION" }); if (result.state === "UNKNOWN") return review(Object.freeze({ ...transaction, payment: "UNKNOWN" }), { reason: result.detail ?? "payment outcome unknown", operation: "PAYMENT", customerActionRequired: false, operatorActionRequired: true }); return Object.freeze({ ...transaction, payment: "FAILED" }); }
export function reconcilePayment(transaction: CommerceTransaction, provider: FakePaymentProvider, key: string): CommerceTransaction { const state = provider.reconcile(key); if (state === "CAPTURED") return Object.freeze({ ...transaction, payment: "CAPTURED", order: { ...transaction.order, state: "CONFIRMED" as OrderState } }); if (state === "UNKNOWN") return review(transaction, { reason: "payment reconciliation unresolved", operation: "PAYMENT", customerActionRequired: false, operatorActionRequired: true }); return Object.freeze({ ...transaction, payment: state }); }
export function submitFulfillment(transaction: CommerceTransaction, provider: FakeFulfillmentProvider, key: string): CommerceTransaction { if (transaction.payment !== "CAPTURED") return transaction; const result = provider.submit(key); if (result.state === "SUCCESS") return Object.freeze({ ...transaction, fulfillment: "ACCEPTED", order: { ...transaction.order, state: "PROCESSING" as OrderState } }); if (result.state === "UNKNOWN") return review(Object.freeze({ ...transaction, fulfillment: "UNKNOWN" }), { reason: result.detail ?? "fulfillment outcome unknown", operation: "FULFILLMENT", customerActionRequired: false, operatorActionRequired: true }); return Object.freeze({ ...transaction, fulfillment: "FAILED" }); }
export function reconcileFulfillment(transaction: CommerceTransaction, provider: FakeFulfillmentProvider, key: string): CommerceTransaction { const state = provider.reconcile(key); if (state === "ACCEPTED") return Object.freeze({ ...transaction, fulfillment: "ACCEPTED", order: { ...transaction.order, state: "PROCESSING" as OrderState } }); if (state === "UNKNOWN") return review(transaction, { reason: "fulfillment reconciliation unresolved", operation: "FULFILLMENT", customerActionRequired: false, operatorActionRequired: true }); return Object.freeze({ ...transaction, fulfillment: state }); }
export function requestRefund(transaction: CommerceTransaction, provider: FakePaymentProvider, key: string): CommerceTransaction { if (transaction.payment !== "CAPTURED" && transaction.payment !== "PARTIALLY_REFUNDED") return transaction; const result = provider.refund(key); if (result.state === "SUCCESS") return Object.freeze({ ...transaction, payment: "REFUNDED" }); if (result.state === "UNKNOWN") return review(Object.freeze({ ...transaction, payment: "PARTIALLY_REFUNDED" }), { reason: "refund outcome unknown", operation: "REFUND", customerActionRequired: false, operatorActionRequired: true }); return Object.freeze({ ...transaction, payment: "PARTIALLY_REFUNDED" }); }

const shipmentRank: Record<ShipmentState, number> = { NOT_REQUIRED: 0, NOT_SHIPPED: 1, PREPARING: 2, LABEL_CREATED: 3, SHIPPED: 4, IN_TRANSIT: 5, OUT_FOR_DELIVERY: 6, DELIVERED: 7, EXCEPTION: 7, RETURNED: 8, LOST: 8, CANCELLED: 8 };
const productionRank: Record<ProductionState, number> = { NOT_REQUIRED: 0, WAITING: 1, PRE_PRODUCTION: 2, IN_PRODUCTION: 3, COMPLETE: 4, BLOCKED: 4, FAILED: 4, CANCELLED: 4 };
export function applyProviderEvent(transaction: CommerceTransaction, event: CommerceEvent): CommerceTransaction { if (transaction.events.some((known) => known.id === event.id)) return transaction; const events = Object.freeze([...transaction.events, event]); if (event.operation === "SHIPMENT" && (event.state in shipmentRank)) { const next = event.state as ShipmentState; return Object.freeze({ ...transaction, shipment: shipmentRank[next] >= shipmentRank[transaction.shipment] ? next : transaction.shipment, events }); } if (event.operation === "PRODUCTION" && (event.state in productionRank)) { const next = event.state as ProductionState; return Object.freeze({ ...transaction, production: productionRank[next] >= productionRank[transaction.production] ? next : transaction.production, events }); } return review(Object.freeze({ ...transaction, events }), { reason: "unknown provider event", operation: event.operation === "REFUND" ? "REFUND" : event.operation as "PAYMENT" | "FULFILLMENT", customerActionRequired: false, operatorActionRequired: true }); }
export function cancellationDisposition(transaction: CommerceTransaction): RecoveryDisposition { return transaction.production === "IN_PRODUCTION" || transaction.fulfillment === "UNKNOWN" ? "MANUAL_REVIEW_REQUIRED" : transaction.shipment === "SHIPPED" || transaction.shipment === "DELIVERED" ? "NON_RETRYABLE" : "RETRYABLE"; }
export function projectTransactionTimeline(transaction: CommerceTransaction): Readonly<{ completed: readonly string[]; current: readonly string[]; action: "NONE" | "CUSTOMER" | "OPERATOR" }> { const completed: string[] = ["ORDER_RECEIVED"]; const current: string[] = []; if (transaction.payment === "CAPTURED") completed.push("PAYMENT_CAPTURED"); if (transaction.payment === "REFUNDED") completed.push("REFUND_COMPLETED"); else if (transaction.payment === "PARTIALLY_REFUNDED") current.push("REFUND_PROCESSING"); if (transaction.payment === "REQUIRES_ACTION") current.push("PAYMENT_REQUIRES_ACTION"); if (transaction.fulfillment === "ACCEPTED") completed.push("FULFILLMENT_ACCEPTED"); if (transaction.fulfillment === "FAILED") current.push("ORDER_PREPARATION_DELAYED"); if (transaction.production === "IN_PRODUCTION") current.push("PRODUCTION_IN_PROGRESS"); if (transaction.shipment === "DELIVERED") completed.push("SHIPMENT_DELIVERED"); else if (transaction.shipment === "IN_TRANSIT") current.push("SHIPMENT_IN_TRANSIT"); else if (transaction.shipment === "EXCEPTION") current.push("SHIPMENT_EXCEPTION"); return Object.freeze({ completed: Object.freeze(completed), current: Object.freeze(current), action: transaction.payment === "REQUIRES_ACTION" ? "CUSTOMER" : transaction.reviews.length ? "OPERATOR" : "NONE" }); }
