import type { Metadata } from "next";
import Link from "next/link";
import Header from "../../Header";

export const metadata: Metadata = { title: "How Custom Gear Works", description: "Understand the intended high-level path for future FAFO Custom Shop projects." };

const STEPS = [
  { number: "01", title: "Bring the Concept", detail: "A future project may begin with an idea, references, sketches, and a description of the requirements." },
  { number: "02", title: "Clarify the Project", detail: "Project details would need to be reviewed and clarified before any item could be represented as approved." },
  { number: "03", title: "Approve Before Listing", detail: "Only approved custom work would be eligible for a future listing or production path." },
  { number: "04", title: "Document the Deployment", detail: "Completed and approved projects may later be eligible for the public gallery or FAFO World recognition." },
];

export default function HowItWorksPage() {
  return <main className="min-h-screen bg-black text-white"><Header /><section className="relative overflow-hidden border-b border-white/10 px-5 py-20 sm:px-10 sm:py-24 lg:px-16 lg:py-32"><div aria-hidden="true" className="pointer-events-none absolute left-1/2 top-0 h-[540px] w-[900px] max-w-full -translate-x-1/2 bg-[radial-gradient(circle,rgba(212,175,55,0.13)_0%,rgba(0,0,0,0)_68%)]" /><div className="relative z-10 mx-auto w-full max-w-7xl"><p className="text-xs font-black uppercase tracking-[0.32em] text-red-600">Custom Shop</p><h1 className="mt-5 max-w-6xl text-5xl font-black uppercase leading-[0.9] tracking-[-0.05em] sm:text-7xl lg:text-9xl">How Custom <span className="block text-[#D4AF37]">Gear Works</span></h1><div className="mt-8 h-px w-24 bg-red-600" /><p className="mt-8 max-w-3xl text-base font-medium leading-8 text-white/65 sm:text-lg sm:leading-9">The intended process moves from an idea and supporting references toward an approved project and, where appropriate, a public deployment.</p></div></section><section className="px-5 py-20 sm:px-10 sm:py-24 lg:px-16 lg:py-32"><div className="mx-auto w-full max-w-7xl"><div className="grid border-t border-white/15 lg:grid-cols-4">{STEPS.map((step) => <article key={step.number} className="border-b border-white/15 py-9 lg:border-b-0 lg:border-r lg:px-7 lg:last:border-r-0"><p className="text-xs font-black tracking-[0.24em] text-red-600">{step.number}</p><h2 className="mt-6 text-2xl font-black uppercase text-white">{step.title}</h2><p className="mt-4 text-sm leading-7 text-white/55">{step.detail}</p></article>)}</div><aside className="mt-10 border border-[#D4AF37]/30 bg-[#D4AF37]/[0.03] p-7 sm:p-9"><p className="text-xs font-black uppercase tracking-[0.22em] text-[#D4AF37]">Informational Process Only</p><p className="mt-4 max-w-4xl text-sm leading-7 text-white/60 sm:text-base">This page does not open submissions or establish pricing, timelines, production acceptance, ownership terms, or fulfillment commitments. Those operational policies require future approval.</p></aside><Link href="/custom-shop" className="mt-10 inline-flex min-h-12 items-center border border-red-600/70 px-7 py-3 text-xs font-black uppercase tracking-[0.18em] text-[#D4AF37] transition hover:bg-red-700/30 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-red-600">Back to Custom Shop</Link></div></section></main>;
}
